theme = 'hugo-theme-relearn'
baseURL = 'https://cegepmv.github.io/420-211'
languageCode = 'fr-fr'
title = 'App Web'

[params]
    linkTitle = 'Applications Web'
    collapsibleMenu = true
    disableLandingPageButton = true
    themeVariant = ['auto', 'zen-light', 'zen-dark', 'blue']
    disableInlineCopyToClipBoard = true
